### ISSUE TITLE
InvalidArgumentException - PHP version

### ISSUE THREAD

**Issue by Yousha** [malios/php-to-ascii-table#2]
I tried to install this package but got error... so I think the version number must be corrected:

**Usage:**
`composer require malios/php-to-ascii-table`

**Output:**
```
  [InvalidArgumentException]
  Could not find package malios/php-to-ascii-table at any version matching your PHP version 5.6.25.0
```

Im using **PHP 5.6 TS 64-bit**

**Comment by malios** [comment]
Hi @Yousha,
This library is built with PHP 7 so it can't run on PHP 5.6.
If you are using Symfony Console, they have very neat table helper. I think they have PHP 5.6 support in version 3.0.
